use serde_json::Value;

const APP_COMMANDS: &[&str] = &[
    "app_status",
    "active_paste_target",
    "preview_clipboard_image_paste",
    "preview_active_clipboard_image_paste",
    "pty_spawn",
    "pty_write",
    "pty_interrupt",
    "pty_resize",
    "pty_kill",
    "pty_ack",
    "clipboard_write_text",
    "clipboard_read_text",
    "open_path",
    "close_paste_session",
];

const TERMINAL_PERMISSIONS: &[&str] = &[
    "allow-app-status",
    "allow-active-paste-target",
    "allow-preview-clipboard-image-paste",
    "allow-preview-active-clipboard-image-paste",
    "allow-pty-spawn",
    "allow-pty-write",
    "allow-pty-interrupt",
    "allow-pty-resize",
    "allow-pty-kill",
    "allow-pty-ack",
    "allow-clipboard-write-text",
    "allow-clipboard-read-text",
    "allow-open-path",
    "allow-close-paste-session",
];

fn handler_commands(source: &str) -> Vec<&str> {
    source
        .split("tauri::generate_handler![")
        .nth(1)
        .expect("application must register a finite command handler")
        .lines()
        .take_while(|line| line.trim() != "])")
        .map(str::trim)
        .map(|command| command.trim_end_matches(','))
        .filter(|command| !command.is_empty())
        .collect()
}

fn manifest_commands(source: &str) -> Vec<&str> {
    source
        .split("const TERMINAL_COMMANDS: &[&str] = &[")
        .nth(1)
        .expect("build must declare a finite command manifest")
        .lines()
        .take_while(|line| line.trim() != "];")
        .map(str::trim)
        .map(|command| command.trim_matches(',').trim_matches('"'))
        .filter(|command| !command.is_empty())
        .collect()
}

#[test]
fn authority_manifest_parsing_accepts_crlf_source() {
    let handler_source = include_str!("../src/lib.rs").replace('\n', "\r\n");
    let build_source = include_str!("../build.rs").replace('\n', "\r\n");

    assert_eq!(handler_commands(&handler_source), APP_COMMANDS);
    assert_eq!(manifest_commands(&build_source), APP_COMMANDS);
}

#[test]
fn authority_manifest_matches_registered_handlers_and_target_capabilities() {
    let handler_source = include_str!("../src/lib.rs");
    let build_source = include_str!("../build.rs");
    let permissions = include_str!("../permissions/terminal.toml");

    assert_eq!(handler_commands(handler_source), APP_COMMANDS);

    assert_eq!(manifest_commands(build_source), APP_COMMANDS);
    assert!(build_source
        .contains(".app_manifest(tauri_build::AppManifest::new().commands(TERMINAL_COMMANDS))"));
    assert_eq!(
        permissions.matches("[[permission]]").count(),
        APP_COMMANDS.len()
    );

    for (command, permission) in APP_COMMANDS.iter().zip(TERMINAL_PERMISSIONS) {
        assert!(
            build_source.contains(&format!("\"{command}\"")),
            "build manifest must register {command}"
        );
        assert!(
            permissions.contains(&format!("identifier = \"{permission}\"")),
            "terminal permission must name {command}"
        );
        assert!(
            permissions.contains(&format!("commands.allow = [\"{command}\"]")),
            "terminal permission must allow only {command}"
        );
        let generated = std::fs::read_to_string(format!(
            "{}/permissions/autogenerated/{command}.toml",
            env!("CARGO_MANIFEST_DIR")
        ))
        .expect("Tauri must generate a command authority contract");
        assert!(generated.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(generated.contains(&format!("commands.deny = [\"{command}\"]")));
    }
}

#[test]
fn target_capabilities_grant_only_the_finite_terminal_authority() {
    for (path, platform) in [
        ("../capabilities/windows.json", "windows"),
        ("../capabilities/linux.json", "linux"),
    ] {
        let capability: Value = serde_json::from_str(
            &std::fs::read_to_string(format!("{}/tests/{path}", env!("CARGO_MANIFEST_DIR")))
                .expect("target capability must exist"),
        )
        .expect("target capability must be valid JSON");
        assert_eq!(capability["windows"], Value::from(["main"]));
        assert_eq!(capability["platforms"], Value::from([platform]));
        assert_eq!(
            capability["permissions"],
            serde_json::to_value(TERMINAL_PERMISSIONS).expect("permission list must serialize")
        );
    }

    let default_capability: Value =
        serde_json::from_str(include_str!("../capabilities/default.json"))
            .expect("default capability must be valid JSON");
    let default_permissions = default_capability["permissions"]
        .as_array()
        .expect("default permissions must be an array");
    assert!(default_permissions.iter().all(|permission| !permission
        .as_str()
        .is_some_and(|value| value.starts_with("allow-"))));
}
